debug: false
server:
    port: 8081
spring:
  datasource:
    url: jdbc:mysql://projectdb.cqkso0b1hltx.ap-south-1.rds.amazonaws.com:3306/bettercinemadb
    username: root
    password: varshithaK
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      
 
   
